### ISSUE TITLE
Refactoring HostController.processRequest()

### ISSUE THREAD

**Issue by thejhh** [sendanor/inventory-backend#11]
This implementation should be splitted to use multiple smaller methods (one for each action) instead of one big method.

...or instead of methods there could be an adapter class between the controller and the repository plugin, which could handle these tasks. The repository plugin would have the lower level methods, and the adapter the upper level implementation, while the `HostController` would just call them through the `RepositoryAdapter`.

**Comment by teijoviinikainen** [comment]
I have been thinking the same. However, I would like to name the new layer as "Service" instead of "Adapter".

**Comment by teijoviinikainen** [comment]
Before implementing #3, this one should be implemented so that refactored codebase can be used.

**Comment by thejhh** [comment]
Here's a short description about terms I use to name my architecture concepts:

I have been using naming `*Service` as a generic term of static libraries (singleton style) implemented as a class with static methods, located in the `src/services` -- and any other class related to them. (A lot like it was in AngularJS.) These may have global state.

Then I use term `*Utils` as a service like that, but it doesn't have (many) relations between its methods, eg. it's just independent package of useful functions. Sometimes I place them `src/utils` but now they are also in `src/services`.

Then there is also `*Manager`, which is like a service, but it's not a global singleton. You can create these managers (`this.fooManager = new FooManager(...)`) and place them in a class as a member (eg. using composition). 

Then there is adapters, which are a compatibility objects joining two objects together. 

Instead of an adapter, maybe manager?

**Comment by teijoviinikainen** [comment]
This one is now pushed to development-teijo branch. MemoryHostRepository was not updated.
