### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by thejhh** [sendanor/inventory-backend#18]
Please improve documentation related to writing HostRepositories:

 * [ ]  Update documentation for interface `HostRepository` to describe neccessary use of related returned values like `SaveState` enum
 * [ ]  Check JSDocs for enum `SaveStatus` and especially document `SaveStatus.NameConflict`

...and any other part of the code that user should know about when writing `HostRepository` implementations.

**Comment by teijoviinikainen** [comment]
HostReposiroty interface was radically simplified and the current documentation slightly improved. Should be ok now.
