### ISSUE TITLE
The data must be removed if a deleted host is patched again

### ISSUE THREAD

**Issue by thejhh** [sendanor/inventory-backend#28]
It seems that if you do: 

```
ib set bar=foo hostname=foo.example.com
ib delete foo
ib set hostname=foo.example.com
```

Then the `bar=foo` is preserved.

If the resource was deleted, `PATCH` should initialize the data from stratch.  

Client is expected to provide all the data again if they want to restore a resource (eg. undo an action in the UI).

**Comment by teijoviinikainen** [comment]
Fixed
